# Generated by Django 3.2.20 on 2025-05-21 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import generator.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsciiArt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled', max_length=100)),
                ('original_image', models.ImageField(upload_to=generator.models.get_upload_path)),
                ('ascii_result', models.TextField()),
                ('width', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
